project 'TagengoExampleApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TagengoExampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TagengoExampleApp

  pod 'KissXML'
  target 'TagengoExampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TagengoExampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
